apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: whereami-ingress
   annotations:
      kubernetes.io/ingress.class: nginx
spec:
  rules:
   - host: "whereaminow.uk"
     http:
       paths:
        - pathType: Prefix
          path: "/"
          backend:
             service: 
               name: whereami
               port:
                 number: 80      