apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: whereami-ingress
    namespace: default
spec:
  ingressClassName: nginx
  rules:
      http:
         paths:
           - pathType: Prefix
             backend:
               service:
                 name: whereami
                 port:
                   number: 80
             path: /
     