---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "whereami-ingress"
  namespace: "default"
spec:
  rules:
  - http:
      paths:
      - path: ""
        backend:
          service:
            name: "whereami"
            port:
              number: 80
        pathType: "ImplementationSpecific"
    host: "whereaminow.uk"
status:
  loadBalancer: {}
