apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whereami
  namespace: default
spec:
  dnsNames:
    - sri.whereaminow.uk
  secretName: wherami-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
