apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whereami
  namespace: default
spec:
  dnsNames:
    - sri.whereaminow.uk
  secretName: whereami-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
